name: Continuous Deployment - postgres

on:
  push:
    branches:
      - main
    paths:
      - 'postgres/**'
      - '.github/workflows/postgres-deployment.yml'

jobs:
  Publish:
    name: Publish image to container registries
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          context: ./postgres
          tags: |
            skyrabot/postgres:latest
            ghcr.io/skyra-project/postgres:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2.4.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: skyrabot/postgres
          readme-filepath: ./postgres/README.md
          short-description: Postgres Database with customized defaults for Skyra Discord bot
